

version: 0.0
os: linux

files:
  - source: index.html
    destination: /var/www/html
  - source: scripts/nginx.conf
    destination: /etc/nginx/nginx.conf

hooks:
  BeforeInstall:
    - location: scripts/install.sh
      runas: root

